theme = "merionette"

[editor]
scrolloff = 25
line-number = "relative"
rulers = [100, 120]
auto-save = true
true-color = true
idle-timeout = 0

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = [
  "file-modification-indicator",
  "file-name",
  "separator",
  "version-control",
  "separator",
]
right = ["position", "position-percentage", "total-line-numbers"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = "⏎ "

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "."
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[keys.normal]
g = { a = "code_action" }
"C-." = "repeat_last_motion"
"space" = { "." = ":toggle-option lsp.display-inlay-hints" }
"G" = "goto_file_end"
"X" = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
"." = ":toggle-option lsp.display-inlay-hints"
q = ":buffer-close"
l = ":sh git log -n 5 --no-patch -L%{cursor_line},+1:%{buffer_name}"

[keys.insert]
j = { k = "normal_mode" }
